### PR TITLE
fix: memory leak, clearTimeout and cancelAnimationFrame on componentWillUnmount

### PR DESCRIPTION
**Pull request by bryan-hunter**
closes https://github.com/tajo/react-movable/issues/73

When the List component is removed (via a click/touch), requestAnimationFrame is executed but not finished, so results in a memory leak.

this PR returns a cancel function from the `schd` util so we can cancel it on unmount. Also added clearTimeout just in case

### CODE REVIEW

**Comment by tajo** [comment]
Nice catch. Thanks. I have to look into CI and will merge after.

**Comment by tajo** [comment]
@bryan-hunter Can you rebase master? It should fix the CI. Thanks

**Comment by mdrobny** [comment]
Any estimates when it will be released?

**Comment by tajo** [comment]
published

**Pull request merged**
